#spring 配置#
spring: 
  redis: 
    host: 127.0.0.1
    database: 1
    port: 6379
    password:
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/hotal?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: zhangtianqi