#spring 配置#
spring:
  redis:
    host: r-bp10105d8e2f59e4.redis.rds.aliyuncs.com
    database: 0
    port: 6379
    password: r-bp10105d8e2f59e4:YY_redisauth123
  datasource: 
    url: jdbc:mysql://rm-bp1989hm1bkputwto2o.mysql.rds.aliyuncs.com:3306/yuyuan_mmc?useUnicode=true&characterEncoding=UTF8&rewriteBatchedStatements=TRUE&allowMultiQueries=true&useSSL=false
    username: mmc_appusr
    password: Udf&#dyP1
  