#spring 配置#
spring: 
  datasource:  
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid: 
      connectionProperties: ''
      filter:
        config:
          enabled: true
        slf4j:
          enabled: true
          statement-executable-sql-log-enable: true
          statement-execute-after-log-enabled: false
          statement-log-enabled: true
          statement-prepare-after-log-enabled: false
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 5000
        wall:
          enabled: false
      initial-size: 1
      max-active: 2000
      max-pool-prepared-statement-per-connection-size: -1
      max-wait: 60000
      min-idle: 1
      pool-prepared-statements: false
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: select 1
      validation-query-timeout: -1
  http:
    encoding.force: true
    multipart:
      max-file-size: 150Mb
      max-request-size: 150Mb
  application.version: '@project.version@'
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: ALWAYS
    deserialization:
      fail-on-unknown-properties: false
    generator:
      write-bigdecimal-as-plain: true
    parser:
      allow-unquoted-field-names: true
      allow-single-quotes: true
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
      write-enums-using-to-string: true
  mvc:
    favicon.enabled: false
    date-format: yyyy-MM-dd HH:mm:ss
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  profiles:
    active: dev
    include: 'datasource'
  application.name: msc-yuyuangarden
  main:
    allow-bean-definition-overriding: true

#服务器配置#
server:
  port: 80
  servlet.context-path: /hotal
  servlet.use-forward-headers: true
  tomcat:
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For
    accept-count: 1000
    max-threads: 1000
    max-connections: 2000


#mybatis配置#
mybatis:
  mapper-locations: classpath:sqlmap/*.xml
  configuration.mapUnderscoreToCamelCase: true
  type-aliases-package: com.xiaoxiao.hotal.entity, com.xiaoxiao.hotal.pojo
  pagehelper.auto-runtime-dialect: true

#日志配置#
logging:
  file: /var/log/xiaoxiao/hotal.log
  config: classpath:logback-spring.xml
  level:
    root: INFO
    com.xiaoxiao: INFO
    druid.sql.DataSource: DEBUG
    druid.sql.Connection: DEBUG
    druid.sql.Statement: DEBUG
    druid.sql.ResultSet: INFO
